version: "3.1"

services:
  yellp-request-gateway:
    build: .
    ports:
      - 8989:8989
    depends_on:
      - mysql
      - rabbitmq
    network_mode: "host"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword

  rabbitmq:
    image: rabbitmq:management
    ports:
    - "5672:5672"
    - "15672:15672"

  adminer:
    image: adminer
    restart: always
    ports:
    - 7777:8080